#pbcopy & pbpaste aliases
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

#clean up system
alias clean='sudo apt clean && sudo apt autoclean && sudo apt autoremove'
